name: CI/CD workflow

on:  
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main  

jobs:  
  build-and-scan:   
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  

      - name: Set up Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.x'  

      - name: Install Semgrep  
        run: pip install semgrep  

      - name: Run Semgrep  
        run: semgrep --config "p/ci" --json > semgrep-output.json 

      - name: Upload Semgrep results  
        if: failure()  
        uses: actions/upload-artifact@v3  
        with:  
          name: semgrep-results  
          path: semgrep-output.json  

      - name: RUN DAST Scan  
        continue-on-error: true  
        uses: PortSwigger/dastardly-github-action@v1.0.0  
        with:  
          target-url: 'http://localhost:9090/'  
          output-filename: 'dastardly-report.xml'  

      - name: Upload Dastardly Report  
        if: always()  
        uses: actions/upload-artifact@v3  
        with:  
          name: dastardly-report  
          path: dastardly-report.xml 

      - name: Upload Reports 
        uses: actions/upload-artifact@v3  
        with: 
          name: All-Reports 
          path: |
            dastardly-report.xml
            semgrep-output.json  

      - name: Execute DefectDojo Script 
        run: python3 defect-dojo.py 
        continue-on-error: true 
        env: 
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }} 
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }} 
          DEFECTDOJO_PRODUCT_ID: ${{ secrets.DEFECTDOJO_PRODUCT_ID }} 
