name: CI/CD workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep
      run: |
        semgrep --config "p/ci"

    - name: Upload Semgrep results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-results
        path: semgrep-output.json

    - name: Post results as a comment
      if: failure()
      run: |
        echo "### Semgrep SAST Results" > comment.md
        cat semgrep-output.json >> comment.md

        - name: DAST Scan
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@v1.0.0
        with:
          target-url: 'http://localhost:9090/'
          output-filename: 'dastardly-report.xml'
        gh pr comment ${{ github.event.pull_request.number }} --body-file comment.md
